# ============================================================
# CONFIGURAÇÕES E CONSTANTES
# ============================================================

LARGURA_JANELA = 480
ALTURA_JANELA  = 480

TAMANHO_CELULA = 24
LARGURA_GRADE = LARGURA_JANELA // TAMANHO_CELULA
ALTURA_GRADE  = ALTURA_JANELA  // TAMANHO_CELULA

FPS = 60
PASSOS_POR_SEGUNDO_INICIO = 8.0
PASSOS_POR_SEGUNDO_MAXIMO = 18.0

TAMANHO_INICIAL = 2
CRESCER_POR_COMIDA = 1

AUMENTA_VELOCIDADE_A_CADA = 5
FATOR_AUMENTO_VELOCIDADE = 1.10

ATRAVESSAR_BORDAS = False

# Cores
COR_FUNDO  = (18, 18, 20)
COR_GRADE  = (40, 40, 44)
COR_COBRA  = (30, 200, 80)
COR_COMIDA = (230, 80, 80)
COR_TEXTO  = (230, 230, 230)
COR_AVISO  = (150, 150, 160)
